In [32]:
from sklearn.datasets import load_diabetes
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

# Example 01

In [33]:
df= pd.DataFrame({'cgpa':[1,3,4,6,7],'iq':[10,14,15,18,20],'package':[9,10,13,14,16]})
df

cgpa  iq  package
0     1  10        9
1     3  14       10
2     4  15       13
3     6  18       14
4     7  20       16

In [35]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [36]:
print(X.shape)
print(y.shape)

(5, 2)
(5,)


In [37]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [38]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [39]:
reg.coef_

array([ 2.7 , -0.95])

In [40]:
reg.intercept_

15.50000000000004

In [41]:
y_pred = reg.predict(X_test)
y_pred

array([12.05])

In [42]:
r2_score(y_test,y_pred)

C:\Users\Faizan computer\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:996: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


nan

In [52]:
class SGDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=10):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [53]:
X_train.shape

(4, 2)

In [54]:
coef_ = np.ones(X_train.shape[1])
coef_

array([1., 1.])

In [55]:
intercept_ = 0

In [58]:
X_train.loc[0]

cgpa     1
iq      10
Name: 0, dtype: int64

In [64]:
np.dot(X_train.loc[1],coef_) + intercept_

17.0

In [65]:
X_train.shape

(4, 2)

In [66]:
class SGDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=10):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0,X_train.shape[0])
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                
                intercept_der = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [71]:
sgd = SGDRegressor(learning_rate=0.01,epochs=1)

In [72]:
np.random.randint(0,X_train.shape[0])

1

In [73]:
sgd.fit(X_train,y_train)

KeyError: 1

# Example 02

In [2]:
X,y = load_diabetes(return_X_y=True)


In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [6]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [7]:
reg.intercept_

151.88331005254167

In [8]:
y_pred = reg.predict(X_test)
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [10]:
r2_score(y_test,y_pred)

0.4399338661568969

#  class SGDRegressor:

In [11]:
class SGDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [12]:
X_train.shape

(353, 10)

In [13]:
coef_ = np.ones(X_train.shape[1])
coef_

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
intercept_ = 0

In [15]:
np.dot(X_train[42],coef_) + intercept_

0.09762897536168798

In [16]:
X_train.shape

(353, 10)

In [ ]:
(1,10) * (1,1) = (10)

# class SGDRegressor by using loop:

In [17]:
class SGDRegressor:
    
    def __init__(self,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx = np.random.randint(0,X_train.shape[0])
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                
                intercept_der = -2 * (y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
                
                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

# 1

In [18]:
sgd = SGDRegressor(learning_rate=0.01,epochs=100)

In [19]:
np.random.randint(0,X_train.shape[0])

187

In [20]:
sgd.fit(X_train,y_train)

158.8804135163475 [  28.02524886 -134.89385226  447.72714585  303.64886387  -17.99261497
  -87.46152828 -188.30269558  109.91117683  407.13282034  112.7581693 ]


In [56]:
y_pred = sgd.predict(X_test)
y_pred

array([150.8654639 , 194.70771606, 130.26500731, 102.72794779,
       258.50363284, 248.02813066, 107.76026582, 112.17057856,
        91.62378064, 185.7403648 , 148.59382543, 172.16991729,
       180.65552541, 138.81142252, 278.79734271,  84.73430197,
       194.40090508, 143.3718412 , 132.85876966, 131.37031624,
       140.44135209, 176.29263623, 155.19533109, 174.49534357,
       124.61544587, 220.61290286, 198.55274149, 104.98706235,
        52.99727328, 238.91705926, 240.57287268, 112.32266486,
        65.78026548,  98.17967519, 201.94158725, 162.67386204,
       162.25943183, 192.80505694, 111.00076864, 237.02097707,
       137.53032486, 120.83938881, 185.07110771, 185.64688666,
       172.68455399, 141.93537755, 170.27492598, 293.24571375,
       107.81694035, 175.33439109, 248.80208111, 135.7651337 ,
       146.8052685 , 131.63251045, 190.35244848,  99.27607869,
       137.37187789,  75.89059117, 156.87194014, 149.24324314,
       162.34960185, 163.6400883 , 102.22839048, 218.91

In [21]:
r2_score(y_test,y_pred)

0.4399338661568969

# 2

In [22]:
sgd = SGDRegressor(learning_rate=0.01,epochs=40)

In [23]:
start = time.time()
sgd.fit(X_train,y_train)
print("The time taken is",time.time() - start)

150.3711376323605 [  60.40003553  -51.60635907  314.70372295  228.92480724   35.61758415
   -5.24271947 -157.26780022  128.54014097  293.11522324  132.77377256]
The time taken is 0.2671494483947754


In [24]:
y_pred = sgd.predict(X_test)

In [25]:
r2_score(y_test,y_pred)

0.41994852841108743

In [26]:
from sklearn.linear_model import SGDRegressor

In [27]:
reg = SGDRegressor(max_iter=100,learning_rate='constant',eta0=0.01)

In [28]:
reg.fit(X_train,y_train)

C:\Users\Faizan computer\anaconda3\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1561: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


SGDRegressor(learning_rate='constant', max_iter=100)

In [29]:
y_pred = reg.predict(X_test)

In [30]:
r2_score(y_test,y_pred)

0.43294282297132247